#!/bin/bash
sudo docker build -t docker_image .

sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query1/original_test.sql --test /usr/bin/scripts/queries/query1/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query2/original_test.sql --test /usr/bin/scripts/queries/query2/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query3/original_test.sql --test /usr/bin/scripts/queries/query3/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query4/original_test.sql --test /usr/bin/scripts/queries/query4/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query5/original_test.sql --test /usr/bin/scripts/queries/query5/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query6/original_test.sql --test /usr/bin/scripts/queries/query6/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query7/original_test.sql --test /usr/bin/scripts/queries/query7/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query8/original_test.sql --test /usr/bin/scripts/queries/query8/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query9/original_test.sql --test /usr/bin/scripts/queries/query9/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query10/original_test.sql --test /usr/bin/scripts/queries/query10/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query11/original_test.sql --test /usr/bin/scripts/queries/query11/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query12/original_test.sql --test /usr/bin/scripts/queries/query12/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query13/original_test.sql --test /usr/bin/scripts/queries/query13/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query14/original_test.sql --test /usr/bin/scripts/queries/query14/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query15/original_test.sql --test /usr/bin/scripts/queries/query15/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query16/original_test.sql --test /usr/bin/scripts/queries/query16/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query17/original_test.sql --test /usr/bin/scripts/queries/query17/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query18/original_test.sql --test /usr/bin/scripts/queries/query18/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query19/original_test.sql --test /usr/bin/scripts/queries/query19/test-script.sh
sudo docker run --rm   -v "$(pwd)/queries-to-minimize:/usr/bin/queries-to-minimize"   docker_image   ./reducer --query /usr/bin/queries-to-minimize/queries/query20/original_test.sql --test /usr/bin/scripts/queries/query20/test-script.sh
